title = "Speechly Docs"
theme = "speechly-docs"
publishDir = "docs"
baseUrl = "https://docs.speechly.com/"
copyright = "Speechly"
languageCode = "en"
enableGitInfo = true
disablePathToLower = true

[markup.goldmark.renderer]
unsafe= true

[markup.tableOfContents]
startLevel = 1
endLevel = 2
ordered = false

[markup.highlight]
style = "solarized-dark"

[taxonomies]
category = "categories"

[params]
description = "Developer tools for next-generation voice user interfaces"
icon_set = "ionicons"

[params.colors]
secondary = "#302666"
primary = "#53A3F9"

[outputs]
home = ["HTML", "JSON"]

[[params.fonts]]
name = "Avenir"
sizes = [400]
type = "sans_serif"

[[params.fonts]]
name = "Sansation"
sizes = [800]
type = "bold"

[[params.fonts]]
name = "Roboto Mono"
sizes = [600]
type = "monospace"

[[menu.main]]
name = "Menu"
weight = 1

[[menu.main]]
name = "Quick Start"
url = "/quick-start/"
weight = 1
parent = "Menu"

[[menu.main]]
name = "Development Tools"
url = "/dev-tools/"
weight = 2
parent = "Menu"

[[menu.main]]
name = "Speechly libraries"
url = "/dev-tools/overview"
weight = 1
parent = "Development Tools"

[[menu.main]]
name = "Client Libraries"
url = "/client-libraries/"
weight = 3
parent = "Menu"

[[menu.main]]
name = "Configuration"
url = "/slu-examples/"
weight = 4
parent = "Menu"

[[menu.main]]
name = "Design"
url = "/design-philosophy/"
weight = 5
parent = "Menu"

[[menu.main]]
name = "How-to guides"
url = "/tutorials/"
weight = 6
parent = "Menu"

[[menu.main]]
name = "Speechly gRPC API"
url = "/speechly-api/"
weight = 7
parent = "Menu"

[[menu.main]]
name = "FAQ"
url = "/faq/"
weight = 8
parent = "Menu"

[[menu.main]]
name = "Product updates"
url = "/release-notes/"
weight = 9
parent = "Menu"

[[menu.main]]
name = "Speechly Website"
weight = 2
url = "https://www.speechly.com"

[[menu.main]]
name = "GitHub"
url = "https://github.com/speechly/"
weight = 3
